### PR TITLE
functions to check for duplicates and to remove duplicates, update ex…

### PR DESCRIPTION
**Pull request by j-c-cook**
functions to check for duplicates and to remove duplicates, update example for borefield definition to show how to use the functions

### CODE REVIEW

**Review by TNWest — APPROVED** [review]

**Review by MassimoCimmino — COMMENTED** [review]
This looks great. If you can update the `CHANGELOG.md`, it will then be ready to merge.

**Comment by j-c-cook** [comment]
Done, as long as that `CHANGELOG.md` message looks okay to you.

**Review by MassimoCimmino — APPROVED** [review]

**Comment by MassimoCimmino** [comment]
@all-contributors add @j-c-cook for code, example, ideas.

**Comment by MassimoCimmino** [comment]
@all-contributors add @j-c-cook for code, example, ideas.

**Pull request merged**
