### PR TITLE
Issue33 commong function interface

### LINKED ISSUE #33: Common interface for all g-function boundary conditions
With the multiplication of borehole boundary conditions, a centralize function would simplify the use of *pygfunction*.

### LINKED ISSUE #54: Documentation of functions related to Cimmino and Bernier 2014
The uniform borehole wall temperature (UBHWT) documentation points to Cimmino and Bernier 2014. Specifically the <a href="https://github.com/MassimoCimmino/pygfunction/blob/982ab6c47dae4931415f1a0f9a43bbfcfb34580c/pygfunction/gfunction.py#L113">uniform_temperature</a> function is an implementation of Boundary Condition 3 (BC-III). Could it be placed in the documentation that it specifically applies to BC-III?

Could the documentation of the <a href="https://github.com/MassimoCimmino/pygfunction/blob/982ab6c47dae4931415f1a0f9a43bbfcfb34580c/pygfunction/gfunction.py#L14">uniform_heat_extraction</a> function point the boundary condition to which is applies from Cimmino and Bernier (2014)?

### LINKED ISSUE #85: Reduce segment responses held in memory
The segment response matrix [h_ij](https://github.com/MassimoCimmino/pygfunction/blob/d48f31099b56e731a4ca5a0998268c1c94ba4602/pygfunction/gfunction.py#L203) is of size `nq x nq x nt`, where `nq` is the number of sources in the field, and `nt` is the number of time steps. 

Two variants of the segment response matrix [h_dt](https://github.com/MassimoCimmino/pygfunction/blob/d48f31099b56e731a4ca5a0998268c1c94ba4602/pygfunction/gfunction.py#L228) and [dh_ij](https://github.com/MassimoCimmino/pygfunction/blob/d48f31099b56e731a4ca5a0998268c1c94ba4602/pygfunction/gfunction.py#L232) are computed. The factor increment matrix `dh_ij` is used in calculating the borehole wall temperatures based on all previous responses, equation 18 from Cimmino (2018). The `h_dt` matrix sets up the linear interpolation for the current thermal response factor matrix [h_ij_dt](https://github.com/MassimoCimmino/pygfunction/blob/d48f31099b56e731a4ca5a0998268c1c94ba4602/pygfunction/gfunction.py#L241), and can be seen in equation 18 in Cimmino (2018). 

With the current methodology here, the segment response matrix `h_ij` is necessary for computing both `h_dt` and `dh_ij`. Therefore, it is not directly possible to get around _having_ to hold `3 (nq x nq x nt)` segment response factors in memory. With each of the segment responses being double precision (at 16 bytes). 

Would it be possible to directly compute [h_ij_dt](https://github.com/MassimoCimmino/pygfunction/blob/d48f31099b56e731a4ca5a0998268c1c94ba4602/pygfunction/gfunction.py#L241) and [dh_ij[:, :, t]](https://github.com/MassimoCimmino/pygfunction/blob/d48f31099b56e731a4ca5a0998268c1c94ba4602/pygfunction/gfunction.py#L768) from `h_ij` without computing `dh_ij` and `h_dt` without losing speed performance? 

-----------------------

Massimo Cimmino (2018) Fast calculation of the g-functions of geothermal borehole fields using similarities in the evaluation of the finite line source solution, Journal of Building Performance Simulation, 11:6, 655-668.

### PR DESCRIPTION
**Pull request by MassimoCimmino**
This closes #33, closes #54, closes #85.

I am opening this PR to get some feedback and review on the new interface (#33). It is mostly complete. The remaining tasks are to
- [x] complete/modify the documentation.
- [x] use the `find_duplicates` function from #81 to check the validy of a bore field layout.
- [x] update `CHANGELOG.md`.

Some highlights:
- I removed functions from `pygfunction.gfunction`, namely `load_history_reconstruction`, `_borehole_segments`, `_temporal_superposition` as they are now part of the new classes.
- I modified the existing examples to use the new interface.
- There are new visualization features in the `gFunction` class. These are demonstrated in the modified examples, e.g. `uniform_temperature.py`.

### CODE REVIEW

**Comment by MassimoCimmino** [comment]
The PR is ready. I squashed commits and rebased the history (trying out for #83).

**Comment by MassimoCimmino** [comment]
@j-c-cook Could you take a look at this PR? It is pretty much complete from my side.

**Comment by j-c-cook** [comment]
@MassimoCimmino I haven't forgot about this. We are finishing up the semester down here and its a wild time. I will get around to this as soon as practical. 

If at some point you feel the need to merge it and I haven't gotten around to looking closely, please feel free to merge.

**Comment by j-c-cook** [comment]
I was studying your equation 18 from Cimmino (2018).

image

In master you pass [dh_ij](https://github.com/MassimoCimmino/pygfunction/blob/ea22569b9afa52d37db29c390dedc268909ed9b3/pygfunction/gfunction.py#L245) to the [_temporal_superposition](https://github.com/MassimoCimmino/pygfunction/blob/ea22569b9afa52d37db29c390dedc268909ed9b3/pygfunction/gfunction.py#L741). However, in this branch you are passing [h_ij](https://github.com/MassimoCimmino/pygfunction/blob/08975c08984f0060eafeb8d2b1f54897800f2761/pygfunction/gfunction.py#L1308) and computing a [dQ](https://github.com/MassimoCimmino/pygfunction/blob/08975c08984f0060eafeb8d2b1f54897800f2761/pygfunction/gfunction.py#L1461) to find the dimensionless borehole wall temperature. 

Did you decide to do this because you thought it was less work on the CPU? Does this provide both a speed increase and a reduction in memory? I remember you saying somewhere that you're getting the right results with this new code, so that leads me to believe this formulation works. Why is it that equation (18) has `Q_reconstructed(Tau_prime)`, but the code makes use of `Q[:, nt-it-1]`?

-------------------
Massimo Cimmino (2018) Fast calculation of the g-functions of geothermal borehole fields using similarities in the evaluation of the finite line source solution, Journal of Building Performance Simulation, 11:6, 655-668.

**Comment by MassimoCimmino** [comment]
The change is motivated by #85. In the PR, `dh_ij[:nSources, :nSource, :nt]` is no longer computed and instead we only have `h_ij[:nSources, :nSources, :(nt+1)]` and `h_dt[:nSources, :nSources]`. We previously had all 3 plus the stored array in the `interp1d` object.

The two formulations of the temporal superposition process are equivalent : `dT = convolution(dh, Q) = convolution(h, dQ)`. I don't see it affecting the CPU time in any significant way but made no attempt to quantify this. The implementation of `_temporal_superposition()` is probably not optimal (it creates a new array of size `nSources x nt` every time step). This is something that could be revisited after #78. The two remaining computational bottleneck in that branch (for large fields) are the construction of `h_ij` from the already computed FLS and the solution of the system of equations (which the optimization of `_temporal_superposition()` may help).

-----------------------

On another note, I noticed there are now unused functions in the `heat_transfer` module : `thermal_response_factors`, `similarities`, `_similarities_group_by_distance`, and `_similarities_one_distance`. These were all transferred to the `Solver` classes. Unless you have any use for them, I propose they be removed.

**Pull request merged**
