### PR TITLE
Issue47 drawborehole

### PR DESCRIPTION
**Pull request by j-c-cook**
Changes: 
- Incorporates Massimo Cimmino `_check_geometry` method d08484244a0c34a9bacc4ada2de75c10e80a6cd6
- Creates example for visualizing a borehole 
  - Initial file creation f13edab77a7911eee8c0eacbaed4f01188ca66c4
  - Add borehole top view plot ba3435a9d948601fbeb5ea5caf68091ba36c7370
  - Reduce line width of pipe lines b10059f3a241530f9eaf2522d3dd0ffc2918ced1

### CODE REVIEW

**Comment by MassimoCimmino** [comment]
@j-c-cook This looks great.

I made some adjustments to the example template and added documentation files on [https://github.com/MassimoCimmino/pygfunction/tree/issue47_drawBorehole_j-c-cook](/MassimoCimmino/pygfunction/tree/issue47_drawBorehole_j-c-cook).

I see git tracks changes on 72 files on this pull request while only 3 Python files saw changes. My searches bring me [https://stackoverflow.com/questions/1580596/how-do-i-make-git-ignore-file-mode-chmod-changes/1580644#1580644](here). This should probably be settled before merging into master.

**Comment by j-c-cook** [comment]
The stackoverflow answer https://stackoverflow.com/a/1580644/11637415 worked great for how to ignore file mode chmod changes. I was unaware of why that was going on. Its a good thing you requested I revert those changes. Does it now look okay in that regard?

I merged your https://github.com/MassimoCimmino/pygfunction/tree/issue47_drawBorehole_j-c-cook additions. **I have added a borehole resistance computation, for during design it is nice to know both geometry is proper and idea of borehole resistance.**

What do you think about the addition of the borehole resistance calculation?

**Comment by MassimoCimmino** [comment]
It looks like the changed files successfully disappeared from the diff.

I fully agree with the calculation of the resistance.

I am unsure if `design` is better than `definition` since the design implies the choice of dimensions/material/etc based on external constraints.

I will review on last time once you confirm you are done with the changes, then I will update the documentation files (*.rst) and it should be ready to merge!

**Comment by j-c-cook** [comment]
Thanks. 

For now I am done with the `custom_borehole_definition` example. I like `definition`; I agree it is more applicable. I've started a branch related to [this][1], and will probably modify the example file to use those custom inputs. 

I think this issue is completed once you have made the modifications you would like to. 

[1]: https://github.com/MassimoCimmino/pygfunction/issues/57

**Pull request merged**
