### PR TITLE
Support finishing up PR for inclined boreholes

### PR DESCRIPTION
**Pull request by j-c-cook**
The following quote is from https://github.com/MassimoCimmino/pygfunction/pull/197#issuecomment-1020113288:
> Remaining tasks:
> 
> * [x]  Complete docstrings
> * [ ]  Format code
> * [x]  Merge [Refactor tests using pytest #191](https://github.com/MassimoCimmino/pygfunction/pull/191)
> * [ ]  Implement tests
> * [ ]  Add an example
> * [x]  Update field visualization functions to include tilt on horizontal view
> * [ ]  Update CHANGELOG
> * [x]  Check for more efficient integration approach
> * [ ]  Consider `'similarities'` and `'equivalent'` implementations
> * [x]  Approximation for inclined boreholes

In this PR I'll be working on documentation (format code, add example, update change log) and make a first pass on implementing tests for inclined boreholes to try to help @MassimoCimmino  wrap inclined borehole work.

### CODE REVIEW

**Comment by j-c-cook** [comment]
@MassimoCimmino Please take a look at my commit message and the editing I have done to `examples/tilted_boreholes.py`, `gt.utilities` and `gt.boreholes`. I'd like to know if you think I should continue down this path I am on. 

Do you want a `tilt` parameter added to all of the built in field generation functions like I have done with `rectangle_field` and you had previously done with `circle_field`? Please note that the current `rectangle_field` logic removes the tilt if its location is at the "origin".

**Comment by MassimoCimmino** [comment]
@j-c-cook Thanks. This is something I had planned.

#### gt.boreholes
It seems your `compute_angle_to()` function is similar to [numpy.arctan2()](https://numpy.org/doc/stable/reference/generated/numpy.arctan2.html). Is there any specific need for this function?

I would suggest an `origin=None` parameter to all field-generating functions. For U-, L-, Box, and rectangular bore fields, this places the origin at then center of the rectangle. Otherwise, an `origin=(x, y)` tuple can be provided for other origin points for orienting boreholes.

I wonder if there is any point in also adding some kind of `twist=0.` parameter (I am open to other variable names). The orientation of boreholes would be calculated from origin plus a constant equal to `twist`.

#### Example
In your example, the diamond field and rectangle field are the same as a circle field with 4 boreholes. I would slightly larger fields. For the custom field, perhaps either of the fan-shaped or optimal configurations of Eskilson:

Capture

I like your use of cardinal directions. It could be beneficial to add a `gt.utilities.orientation()` function, with e.g. `gt.utilities.orientation('north') = gt.utilities.orientation('N') = np.pi/2`, `gt.utilities.orientation('northeast') = gt.utilities.orientation('NE') = np.pi/4`, `gt.utilities.orientation('east-northeast') = gt.utilities.orientation('ENE') = np.pi/8`, etc.

#### Solvers
On your note:
https://github.com/MassimoCimmino/pygfunction/blob/e8ce2092c6254e1b025e1cb0e119093d6686a59d/examples/inclined_boreholes.py#L67

The `similarities` solver already has an initial implementation for inclined boreholes. I'm giving another try at extending the `equivalent` solver soon.

I will very likely refactor code in the solvers so it is still too early to work on code formatting in the `heat_transfer` and `gfunction` modules.

**Comment by j-c-cook** [comment]
@MassimoCimmino  I have made updates based on your comments. Details can be found in my latest [commit message](https://github.com/MassimoCimmino/pygfunction/pull/203/commits/27c06cd30312206bb2c04a23f7f9fc1b1c02ba61). Formatting is not as clean as it could be as I'd like to make cleanup more of a last step once functionality is resolved.

Could you let me know what you think about the current changes, and if you think I should address anything else associated with the example?

I'm considering taking a stab at addressing tests.

**Comment by j-c-cook** [comment]
I documented changes made to the `boreholes` module in https://github.com/MassimoCimmino/pygfunction/pull/203/commits/27c06cd30312206bb2c04a23f7f9fc1b1c02ba61, but did not add the changes associated with the file to the commit. My recent push updates the `boreholes`. The changes are somewhat cleaned and formatted in https://github.com/MassimoCimmino/pygfunction/pull/203/commits/aaf2907ec46f1cc9db9497383e346a447418d01e.

**Comment by j-c-cook** [comment]
This branch contains all of my changes made. @MassimoCimmino you're good to merge.

**Pull request merged**
