### PR TITLE
Add upload to pypi step in workflow

### LINKED ISSUE #230: Publish on release workflow
Did version 2.2.0 never get pushed onto [PyPi](https://pypi.org/project/pygfunction/#history)? Would you want to setup a [publish on release](https://github.com/j-c-cook/ghedt/blob/main/.github/workflows/python-publish.yml) workflow file? I remember thinking pre-releases don't trigger this workflow.

### PR DESCRIPTION
**Pull request by j-c-cook**
closes #230

### CODE REVIEW

**Comment by MassimoCimmino** [comment]
Thanks @j-c-cook.

Is there a way to test this without publishing a release, or do we have to test it on a release candidate version?

I probably need to configure the secrets on the project.

**Comment by mitchute** [comment]
@MassimoCimmino you can configure it to push to https://test.pypi.org/ for testing purposes. You may need to modify the deployment action to include a `repository_url`, and then have separate secrets for test.pypi.org.

**Comment by j-c-cook** [comment]
Without modifying the current workflow, I think you would need to publish a release candidate to test it. 

Matt seems to be proposing an alternative. Which would require `if: github.event.release && github.event.action == 'published'` to be temporarily removed for the test to run without a release being created.

**Comment by j-c-cook** [comment]
> @MassimoCimmino see here for an example. Changing the url to `https://test.upload.pypi.org/legacy/` will push it to test.pypi.org if you like during your testing.

Please note that "here" is not currently a hyper-reference.

**Comment by mitchute** [comment]
This link for example: https://github.com/mitchute/SecondaryCoolantProps/blob/cdd09459f1a692aaef2924125264753a36a2841d/.github/workflows/release.yml

**Review by MassimoCimmino — APPROVED** [review]

**Pull request merged**
